export const QA_DATA = [
  { q: "What is Cordyceps militaris?", a: "It is a medicinal mushroom known for boosting immunity and energy." },
  { q: "Is Cordyceps farming profitable?", a: "Yes, it has high market value and good demand in health products." },
  { q: "What temperature is required?", a: "Around 18°C to 22°C is ideal." },
  { q: "What humidity is needed?", a: "Maintain 70% to 80% humidity." },
  { q: "How many days to grow?", a: "Usually 45 to 60 days." },
  { q: "What substrate is used?", a: "Rice, silkworm pupae, or nutrient-rich grains." },
  { q: "Can beginners grow it?", a: "Yes, with proper guidance and hygiene." },
  { q: "Is sunlight required?", a: "No direct sunlight, only indirect light." },
  { q: "How to avoid contamination?", a: "Maintain cleanliness and sterilize all materials." },
  { q: "What is the yield per bottle?", a: "Around 15–25 grams (varies)." },
  { q: "How to dry Cordyceps?", a: "Use low heat drying or freeze drying." },
  { q: "Can I grow at home?", a: "Yes, in a controlled indoor environment." },
  { q: "What equipment is needed?", a: "Incubator, humidity controller, jars/bottles." },
  { q: "Is it legal to grow?", a: "Yes, but check local regulations." },
  { q: "What is cordycepin?", a: "A bioactive compound with medicinal benefits." },
  { q: "What are common mistakes?", a: "Poor hygiene, wrong temperature, overwatering." },
  { q: "How to store after harvest?", a: "Store in airtight containers." },
  { q: "Can it be sold online?", a: "Yes, as dried product or supplements." },
  { q: "What is the market price?", a: "It varies, but generally high value." },
  { q: "Do I need training?", a: "Basic training is recommended." },
  { q: "Can I scale this business?", a: "Yes, it has strong scalability." },
  { q: "What light is needed?", a: "Low-intensity LED light." },
  { q: "What is incubation?", a: "The stage where mycelium grows." },
  { q: "What is fruiting stage?", a: "When mushrooms start growing." },
  { q: "How to increase yield?", a: "Maintain proper conditions and nutrients." },
  { q: "What is contamination color?", a: "Green or black spots indicate contamination." },
  { q: "Can I automate farming?", a: "Yes, using IoT systems." },
  { q: "What is ROI?", a: "Return on investment can be high with scale." },
  { q: "Can I export?", a: "Yes, demand exists globally." },
  { q: "Is it safe to consume?", a: "Yes, when grown properly." },
  { q: "Can I reuse substrate?", a: "Not recommended due to contamination risk." },
  { q: "What is the best beginner setup?", a: "Small indoor controlled setup." },
  { q: "How to check quality?", a: "Bright orange color and firm texture." },
  { q: "What are its health benefits?", a: "Boosts immunity, energy, and stamina." },
  { q: "Can AI help in farming?", a: "Yes, for monitoring and automation." },
  { q: "What is the first step in Cordyceps cultivation?", a: "Start by preparing a clean and sterile working environment." },
  { q: "Why is sterilization important?", a: "It prevents contamination from bacteria and unwanted fungi." },
  { q: "What substrate is best for beginners?", a: "Rice-based substrate is simple and effective." },
  { q: "How do I prepare the substrate?", a: "Soak rice, drain excess water, and fill into jars or bottles." },
  { q: "How to sterilize the substrate?", a: "Use a pressure cooker at 121°C for 15–30 minutes." },
  { q: "What is inoculation?", a: "It is the process of adding Cordyceps culture to the substrate." },
  { q: "Where to get the culture?", a: "From trusted labs or mushroom suppliers." },
  { q: "How to do inoculation safely?", a: "Work in a clean space using gloves and sanitized tools." },
  { q: "What happens after incubation?", a: "Move to fruiting conditions." },
  { q: "What causes contamination?", a: "Poor hygiene and improper sterilization." },
  { q: "What containers are used?", a: "Glass jars or polypropylene bottles." },
  { q: "Can I use tap water?", a: "Use clean or filtered water." },
  { q: "How to harvest?", a: "Gently pull or cut from the base." },
  { q: "What is airflow importance?", a: "Fresh air prevents contamination and supports growth." },
  { q: "What is the success key?", a: "Cleanliness, consistency, and monitoring." }
];
